import Foundation

/// Root structure of xcstrings file
package struct XCStringsFile: Codable, Sendable {
    var sourceLanguage: String
    var strings: [String: StringEntry]
    var version: String

    package init(sourceLanguage: String = "en", strings: [String: StringEntry] = [:], version: String = "1.0") {
        self.sourceLanguage = sourceLanguage
        self.strings = strings
        self.version = version
    }
}

/// String entry for each key
package struct StringEntry: Codable, Sendable {
    var comment: String?
    var isCommentAutoGenerated: Bool?
    var shouldTranslate: Bool?
    var extractionState: String?
    var localizations: [String: Localization]?

    package init(
        comment: String? = nil,
        isCommentAutoGenerated: Bool? = nil,
        shouldTranslate: Bool? = nil,
        extractionState: String? = nil,
        localizations: [String: Localization]? = nil
    ) {
        self.comment = comment
        self.isCommentAutoGenerated = isCommentAutoGenerated
        self.shouldTranslate = shouldTranslate
        self.extractionState = extractionState
        self.localizations = localizations
    }
}

/// Localization entry
package struct Localization: Codable, Sendable {
    var stringUnit: StringUnit?
    var variations: Variations?

    package init(stringUnit: StringUnit? = nil, variations: Variations? = nil) {
        self.stringUnit = stringUnit
        self.variations = variations
    }
}

/// String unit containing the actual translation value
package struct StringUnit: Codable, Sendable {
    var state: String
    var value: String

    package init(state: String = "translated", value: String) {
        self.state = state
        self.value = value
    }
}

/// Variations (plural, device, etc.)
package struct Variations: Codable, Sendable {
    var plural: PluralVariation?
    var device: DeviceVariation?

    package init(plural: PluralVariation? = nil, device: DeviceVariation? = nil) {
        self.plural = plural
        self.device = device
    }
}

/// Wrapper for a variation category value (e.g. each plural form or device category)
/// In xcstrings JSON, each variation value is `{ "stringUnit": { "state": "...", "value": "..." } }`
package struct VariationValue: Codable, Sendable {
    var stringUnit: StringUnit?

    package init(stringUnit: StringUnit? = nil) {
        self.stringUnit = stringUnit
    }
}

/// Plural variation
package struct PluralVariation: Codable, Sendable {
    var zero: VariationValue?
    var one: VariationValue?
    var two: VariationValue?
    var few: VariationValue?
    var many: VariationValue?
    var other: VariationValue?

    package init(
        zero: VariationValue? = nil,
        one: VariationValue? = nil,
        two: VariationValue? = nil,
        few: VariationValue? = nil,
        many: VariationValue? = nil,
        other: VariationValue? = nil
    ) {
        self.zero = zero
        self.one = one
        self.two = two
        self.few = few
        self.many = many
        self.other = other
    }
}

/// Device variation
package struct DeviceVariation: Codable, Sendable {
    var iphone: VariationValue?
    var ipad: VariationValue?
    var mac: VariationValue?
    var applewatch: VariationValue?
    var appletv: VariationValue?

    package init(
        iphone: VariationValue? = nil,
        ipad: VariationValue? = nil,
        mac: VariationValue? = nil,
        applewatch: VariationValue? = nil,
        appletv: VariationValue? = nil
    ) {
        self.iphone = iphone
        self.ipad = ipad
        self.mac = mac
        self.applewatch = applewatch
        self.appletv = appletv
    }
}

// MARK: - Output Models

package enum CoverageState: String, Codable, Sendable {
    case measured
    case notApplicable
}

package struct CoverageMeasurement: Codable, Sendable {
    package let state: CoverageState
    let rawPercent: Decimal?

    package var percent: Double? {
        rawPercent.map(Self.serializedPercent(from:))
    }

    package init(state: CoverageState, rawPercent: Decimal?) {
        self.state = state
        self.rawPercent = rawPercent
    }

    package init(state: CoverageState, percent: Double?) {
        self.init(state: state, rawPercent: percent.flatMap(Self.decimalPercent(from:)))
    }

    private enum CodingKeys: String, CodingKey {
        case state
        case percent
    }

    package init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.state = try container.decode(CoverageState.self, forKey: .state)
        if let percent = try container.decodeIfPresent(Decimal.self, forKey: .percent) {
            self.rawPercent = percent
        } else {
            let percent = try container.decodeIfPresent(Double.self, forKey: .percent)
            self.rawPercent = percent.flatMap(Self.decimalPercent(from:))
        }
    }

    package func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(state, forKey: .state)

        if let rawPercent {
            try container.encode(Self.serializedPercentDecimal(from: rawPercent), forKey: .percent)
        } else {
            try container.encodeNil(forKey: .percent)
        }
    }
}

/// Key information for output
package struct KeyInfo: Codable, Sendable {
    package let key: String
    package let comment: String?
    package let isCommentAutoGenerated: Bool?
    package let shouldTranslate: Bool?
    package let extractionState: String?
    package let languages: [String]
    package let translations: [String: TranslationInfo]

    package init(
        key: String,
        comment: String?,
        isCommentAutoGenerated: Bool?,
        shouldTranslate: Bool?,
        extractionState: String?,
        languages: [String],
        translations: [String: TranslationInfo]
    ) {
        self.key = key
        self.comment = comment
        self.isCommentAutoGenerated = isCommentAutoGenerated
        self.shouldTranslate = shouldTranslate
        self.extractionState = extractionState
        self.languages = languages
        self.translations = translations
    }
}

/// Translation information for output
package struct TranslationInfo: Codable, Sendable {
    package let key: String
    package let language: String
    package let value: String?
    package let state: String?
    package let hasVariations: Bool

    package init(key: String, language: String, value: String?, state: String?, hasVariations: Bool) {
        self.key = key
        self.language = language
        self.value = value
        self.state = state
        self.hasVariations = hasVariations
    }
}

/// Coverage information for output
package struct CoverageInfo: Codable, Sendable {
    package let key: String
    package let translatedLanguages: [String]
    package let missingLanguages: [String]
    package let coverage: CoverageMeasurement

    package init(key: String, translatedLanguages: [String], missingLanguages: [String], coverage: CoverageMeasurement) {
        self.key = key
        self.translatedLanguages = translatedLanguages
        self.missingLanguages = missingLanguages
        self.coverage = coverage
    }
}

/// Overall statistics for output
package struct StatsInfo: Codable, Sendable {
    package let totalKeys: Int
    package let sourceLanguage: String
    package let languages: [String]
    package let coverageByLanguage: [String: LanguageStats]

    package init(totalKeys: Int, sourceLanguage: String, languages: [String], coverageByLanguage: [String: LanguageStats]) {
        self.totalKeys = totalKeys
        self.sourceLanguage = sourceLanguage
        self.languages = languages
        self.coverageByLanguage = coverageByLanguage
    }
}

/// Per-language statistics
package struct LanguageStats: Codable, Sendable {
    package let translated: Int
    package let untranslated: Int
    package let total: Int
    package let coverage: CoverageMeasurement

    package init(translated: Int, untranslated: Int, total: Int, coverage: CoverageMeasurement) {
        self.translated = translated
        self.untranslated = untranslated
        self.total = total
        self.coverage = coverage
    }
}

/// Token-efficient batch coverage summary for multiple files
package struct BatchCoverageSummary: Codable, Sendable {
    package let files: [FileCoverageSummary]
    package let aggregated: AggregatedCoverage

    package init(files: [FileCoverageSummary], aggregated: AggregatedCoverage) {
        self.files = files
        self.aggregated = aggregated
    }
}

/// Compact coverage summary for a single file
package struct FileCoverageSummary: Codable, Sendable {
    package let file: String
    package let totalKeys: Int
    package let languages: [String: CoverageMeasurement]

    package init(file: String, totalKeys: Int, languages: [String: CoverageMeasurement]) {
        self.file = file
        self.totalKeys = totalKeys
        self.languages = languages
    }
}

/// Aggregated coverage across all files
package struct AggregatedCoverage: Codable, Sendable {
    package let totalFiles: Int
    package let totalKeys: Int
    package let averageCoverageByLanguage: [String: CoverageMeasurement]

    package init(totalFiles: Int, totalKeys: Int, averageCoverageByLanguage: [String: CoverageMeasurement]) {
        self.totalFiles = totalFiles
        self.totalKeys = totalKeys
        self.averageCoverageByLanguage = averageCoverageByLanguage
    }
}

// MARK: - Compact Output Models (100% languages omitted)

package enum CompactCompletionState: String, Codable, Sendable {
    case complete
    case incomplete
    case notApplicable
}

/// Compact stats info - shows incomplete languages and tracks not-applicable ones separately
package struct CompactStatsInfo: Codable, Sendable {
    package let totalKeys: Int
    package let sourceLanguage: String
    package let totalLanguages: Int
    package let completionState: CompactCompletionState
    package let incompleteLanguages: [String: LanguageStats]?
    package let notApplicableLanguages: [String]?
    package let completeCount: Int
    package let notApplicableCount: Int

    package init(from stats: StatsInfo) {
        self.totalKeys = stats.totalKeys
        self.sourceLanguage = stats.sourceLanguage
        self.totalLanguages = stats.languages.count

        let incomplete = stats.coverageByLanguage.filter { $0.value.coverage.isIncomplete }
        let notApplicable = stats.coverageByLanguage
            .filter { $0.value.coverage.isNotApplicable }
            .keys
            .sorted()
        self.completionState = .from(
            totalLanguages: stats.coverageByLanguage.count,
            incompleteCount: incomplete.count,
            notApplicableCount: notApplicable.count
        )
        self.incompleteLanguages = incomplete.isEmpty ? nil : incomplete
        self.notApplicableLanguages = notApplicable.isEmpty ? nil : notApplicable
        self.completeCount = stats.coverageByLanguage.count - incomplete.count - notApplicable.count
        self.notApplicableCount = notApplicable.count
    }
}

/// Compact file coverage summary - shows incomplete languages and tracks not-applicable ones separately
package struct CompactFileCoverageSummary: Codable, Sendable {
    package let file: String
    package let totalKeys: Int
    package let totalLanguages: Int
    package let completionState: CompactCompletionState
    package let incompleteLanguages: [String: CoverageMeasurement]?
    package let notApplicableLanguages: [String]?
    package let completeCount: Int
    package let notApplicableCount: Int

    package init(from summary: FileCoverageSummary) {
        self.file = summary.file
        self.totalKeys = summary.totalKeys
        self.totalLanguages = summary.languages.count

        let incomplete = summary.languages.filter { $0.value.isIncomplete }
        let notApplicable = summary.languages
            .filter { $0.value.isNotApplicable }
            .keys
            .sorted()
        self.completionState = .from(
            totalLanguages: summary.languages.count,
            incompleteCount: incomplete.count,
            notApplicableCount: notApplicable.count
        )
        self.incompleteLanguages = incomplete.isEmpty ? nil : incomplete
        self.notApplicableLanguages = notApplicable.isEmpty ? nil : notApplicable
        self.completeCount = summary.languages.count - incomplete.count - notApplicable.count
        self.notApplicableCount = notApplicable.count
    }
}

/// Compact batch coverage summary
package struct CompactBatchCoverageSummary: Codable, Sendable {
    package let files: [CompactFileCoverageSummary]
    package let aggregated: CompactAggregatedCoverage

    package init(from batch: BatchCoverageSummary) {
        self.files = batch.files.map { CompactFileCoverageSummary(from: $0) }
        self.aggregated = CompactAggregatedCoverage(from: batch.aggregated)
    }
}

/// Compact aggregated coverage
package struct CompactAggregatedCoverage: Codable, Sendable {
    package let totalFiles: Int
    package let totalKeys: Int
    package let totalLanguages: Int
    package let completionState: CompactCompletionState
    package let incompleteLanguages: [String: CoverageMeasurement]?
    package let notApplicableLanguages: [String]?
    package let completeCount: Int
    package let notApplicableCount: Int

    package init(from agg: AggregatedCoverage) {
        self.totalFiles = agg.totalFiles
        self.totalKeys = agg.totalKeys
        self.totalLanguages = agg.averageCoverageByLanguage.count

        let incomplete = agg.averageCoverageByLanguage.filter { $0.value.isIncomplete }
        let notApplicable = agg.averageCoverageByLanguage
            .filter { $0.value.isNotApplicable }
            .keys
            .sorted()
        self.completionState = .from(
            totalLanguages: agg.averageCoverageByLanguage.count,
            incompleteCount: incomplete.count,
            notApplicableCount: notApplicable.count
        )
        self.incompleteLanguages = incomplete.isEmpty ? nil : incomplete
        self.notApplicableLanguages = notApplicable.isEmpty ? nil : notApplicable
        self.completeCount = agg.averageCoverageByLanguage.count - incomplete.count - notApplicable.count
        self.notApplicableCount = notApplicable.count
    }
}

package extension CompactCompletionState {
    static func from(totalLanguages: Int, incompleteCount: Int, notApplicableCount: Int) -> CompactCompletionState {
        if totalLanguages == 0 || notApplicableCount == totalLanguages {
            return .notApplicable
        }

        if incompleteCount > 0 {
            return .incomplete
        }

        return .complete
    }
}

package extension CoverageMeasurement {
    private static let serializedPercentScale = 2
    private static let percentLocale = Locale(identifier: "en_US_POSIX")
    private static let hundred = Decimal(100)
    private static let zero = Decimal.zero
    private static let smallestSerializedStep = Decimal(string: "0.01", locale: percentLocale)!

    static func measured(_ percent: Double) -> CoverageMeasurement {
        CoverageMeasurement(state: .measured, rawPercent: decimalPercent(from: percent))
    }

    static func measured(_ percent: Decimal) -> CoverageMeasurement {
        CoverageMeasurement(state: .measured, rawPercent: percent)
    }

    static func measured(translated: Int, total: Int) -> CoverageMeasurement {
        guard total > 0 else {
            return .notApplicable
        }

        let percent = (Decimal(translated) * hundred) / Decimal(total)
        return measured(percent)
    }

    static var notApplicable: CoverageMeasurement {
        CoverageMeasurement(state: .notApplicable, rawPercent: nil)
    }

    private static func decimalPercent(from percent: Double) -> Decimal? {
        guard percent.isFinite else {
            return nil
        }

        return Decimal(string: String(percent), locale: percentLocale)
            ?? NSDecimalNumber(value: percent).decimalValue
    }

    private static func serializedPercent(from rawPercent: Decimal) -> Double {
        let roundedPercent = serializedPercentDecimal(from: rawPercent)
        let percent = NSDecimalNumber(decimal: roundedPercent).doubleValue
        return percent == 0 ? 0 : percent
    }

    private static func serializedPercentDecimal(from rawPercent: Decimal) -> Decimal {
        var decimalPercent = rawPercent
        var roundedDecimal = Decimal()
        NSDecimalRound(&roundedDecimal, &decimalPercent, serializedPercentScale, .plain)

        // Coverage that is still incomplete should never be surfaced as 100%.
        if rawPercent < hundred, roundedDecimal >= hundred {
            return hundred - smallestSerializedStep
        }

        return roundedDecimal
    }

    var isComplete: Bool {
        state == .measured && rawPercent == Self.hundred
    }

    var isIncomplete: Bool {
        state == .measured && (rawPercent ?? Self.zero) < Self.hundred
    }

    var isNotApplicable: Bool {
        state == .notApplicable
    }
}

// MARK: - Batch Operation Models

/// Result of batch key existence check
package struct BatchCheckKeysResult: Codable, Sendable {
    package let results: [String: Bool]  // key -> exists
    package let existingKeys: [String]
    package let missingKeys: [String]

    package init(results: [String: Bool]) {
        self.results = results
        self.existingKeys = results.filter { $0.value }.keys.sorted()
        self.missingKeys = results.filter { !$0.value }.keys.sorted()
    }
}

/// Single entry for batch add/update operations
package struct BatchTranslationEntry: Codable, Sendable {
    package let key: String
    package let translations: [String: String]  // language -> value

    package init(key: String, translations: [String: String]) {
        self.key = key
        self.translations = translations
    }
}

/// Result of batch add/update operations
package struct BatchWriteResult: Codable, Sendable {
    package let success: Bool
    package let successCount: Int
    package let failedCount: Int
    package let succeeded: [String]
    package let failed: [BatchWriteError]

    package init(succeeded: [String], failed: [BatchWriteError]) {
        self.success = failed.isEmpty
        self.successCount = succeeded.count
        self.failedCount = failed.count
        self.succeeded = succeeded
        self.failed = failed
    }

    private enum CodingKeys: String, CodingKey {
        case success, successCount, failedCount, succeeded, failed
    }

    package func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(successCount, forKey: .successCount)
        try container.encode(failedCount, forKey: .failedCount)
        // Only include non-empty arrays
        if !succeeded.isEmpty {
            try container.encode(succeeded, forKey: .succeeded)
        }
        if !failed.isEmpty {
            try container.encode(failed, forKey: .failed)
        }
    }
}

/// Error info for batch write operations
package struct BatchWriteError: Codable, Sendable {
    package let key: String
    package let error: String

    package init(key: String, error: String) {
        self.key = key
        self.error = error
    }
}

// MARK: - Stale Keys Models

/// Constants for stale keys messages
package enum StaleKeysConstants {
    package static let note = "These keys are marked as 'stale' by Xcode, indicating they may no longer be used in source code. Please verify by searching for these keys in the module or project source code before deleting them."
}

/// Stale keys for a single file
package struct FileStaleKeysSummary: Codable, Sendable {
    package let file: String
    package let staleKeys: [String]
    package let count: Int

    package init(file: String, staleKeys: [String]) {
        self.file = file
        self.staleKeys = staleKeys
        self.count = staleKeys.count
    }
}

/// Stale keys result for a single file
package struct StaleKeysResult: Codable, Sendable {
    package let staleKeys: [String]
    package let count: Int
    package let note: String

    package init(staleKeys: [String]) {
        self.staleKeys = staleKeys
        self.count = staleKeys.count
        self.note = StaleKeysConstants.note
    }
}

/// Batch stale keys summary for multiple files
package struct BatchStaleKeysSummary: Codable, Sendable {
    package let files: [FileStaleKeysSummary]
    package let totalStaleKeys: Int
    package let note: String

    package init(files: [FileStaleKeysSummary]) {
        self.files = files
        self.totalStaleKeys = files.reduce(0) { $0 + $1.count }
        self.note = StaleKeysConstants.note
    }
}
