import Foundation
import Testing
@testable import XCStringsKit

@Suite("Preflight locale classifier")
struct PreflightClassifierTests {
    @Test("preflightLocale classifies target locale work by write risk")
    func preflightLocaleClassifiesWork() throws {
        let file = try loadFixture(TestFixtures.preflightMixedCatalog)
        let report = XCStringsPreflightClassifier(file: file).preflightLocale("es")

        #expect(report.sourceLanguage == "en")
        #expect(report.targetLanguage == "es")
        #expect(report.missingSimpleStringUnitKeys.map(\.key) == ["plain.missing", "stale.missing"])
        #expect(report.missingFormatStringKeys.map(\.key) == ["format.missing"])
        #expect(report.missingVariationKeys.map(\.key) == ["variation.missing"])
        #expect(report.missingSubstitutionKeys.map(\.key) == ["substitution.missing"])
        #expect(report.nonTranslatableKeys.map(\.key) == ["brand.name"])
        #expect(report.staleKeys.map(\.key) == ["stale.missing"])
        #expect(report.translatedKeys.map(\.key) == ["already.translated"])
        #expect(report.unsafeToWriteKeys.map(\.key) == ["brand.name", "substitution.missing", "variation.missing"])

        #expect(report.summary.totalKeys == 7)
        #expect(report.summary.translatableKeys == 6)
        #expect(report.summary.translatedKeys == 1)
        #expect(report.summary.untranslatedKeys == 5)
        #expect(report.summary.safeToBatchAddKeys == ["plain.missing", "stale.missing"])
        #expect(report.summary.formatStringKeysRequiringValidation == ["format.missing"])
        #expect(report.summary.richKeysRequiringSpecialHandling == ["substitution.missing", "variation.missing"])
        #expect(report.summary.skipKeys == ["brand.name"])
    }

    @Test("compact preflight report keeps planning counts and key lists")
    func compactPreflightReportKeepsPlanningCountsAndKeyLists() throws {
        let file = try loadFixture(TestFixtures.preflightMixedCatalog)
        let report = XCStringsPreflightClassifier(file: file).preflightLocale("es")
        let compact = report.compact

        #expect(compact.sourceLanguage == "en")
        #expect(compact.targetLanguage == "es")
        #expect(compact.summary.missingSimpleKeys == 2)
        #expect(compact.summary.missingFormatKeys == 1)
        #expect(compact.summary.missingRichKeys == 2)
        #expect(compact.summary.unsafeKeys == 3)
        #expect(compact.summary.alreadyTranslatedKeys == 1)
        #expect(compact.safeKeys == ["plain.missing", "stale.missing"])
        #expect(compact.formatSensitiveKeys == ["format.missing"])
        #expect(compact.richOrUnsafeKeys == ["brand.name", "substitution.missing", "variation.missing"])
        #expect(compact.skipKeys == ["brand.name"])
    }

    @Test("preflightLocale includes source metadata and placeholders")
    func preflightLocaleIncludesSourceMetadataAndPlaceholders() throws {
        let file = try loadFixture(TestFixtures.preflightMixedCatalog)
        let report = XCStringsPreflightClassifier(file: file).preflightLocale("es")

        let plain = try #require(report.missingSimpleStringUnitKeys.first { $0.key == "plain.missing" })
        #expect(plain.sourceValue == "Import")
        #expect(plain.comment == "Simple button title.")
        #expect(plain.isCommentAutoGenerated == true)
        #expect(plain.writeSafety.level == .safePlainStringUnit)

        let format = try #require(report.missingFormatStringKeys.first)
        #expect(format.contentKind == .formatString)
        #expect(format.extractionState == "manual")
        #expect(format.placeholderMetadata.sourcePlaceholders.map(\.raw) == ["%1$@", "%2$lld"])
        #expect(format.placeholderMetadata.sourcePlaceholders.map(\.specifier) == ["@", "lld"])
        #expect(format.writeSafety.level == .requiresFormatStringValidation)

        let substitution = try #require(report.missingSubstitutionKeys.first)
        #expect(substitution.placeholderMetadata.sourcePlaceholders.map(\.raw) == ["%#@itemCount@"])
        #expect(substitution.placeholderMetadata.substitutions.map(\.name) == ["itemCount"])
        #expect(substitution.placeholderMetadata.substitutions.first?.argNum == 1)
        #expect(substitution.placeholderMetadata.substitutions.first?.formatSpecifier == "lld")
        #expect(substitution.placeholderMetadata.substitutions.first?.variationPlaceholders.map(\.category) == ["one", "other"])

        let variation = try #require(report.missingVariationKeys.first)
        #expect(variation.sourceValue == "variation.missing")
        #expect(variation.placeholderMetadata.variationPlaceholders.map(\.value) == ["%lld item", "%lld items"])
        #expect(variation.placeholderMetadata.variationPlaceholders.flatMap(\.placeholders).map(\.raw) == ["%lld", "%lld"])
    }

    @Test("preflightLocale sorts entries without relying on insertion order")
    func preflightLocaleSortsEntriesWithoutRelyingOnInsertionOrder() throws {
        var strings = OrderedStringDictionary<StringEntry>()
        strings["z.missing"] = stringEntry(sourceValue: "Z")
        strings["a.missing"] = stringEntry(sourceValue: "A")
        strings["m.missing"] = stringEntry(sourceValue: "M")

        let file = XCStringsFile(sourceLanguage: "en", strings: strings)
        let report = XCStringsPreflightClassifier(file: file).preflightLocale("es")

        #expect(report.missingSimpleStringUnitKeys.map(\.key) == ["a.missing", "m.missing", "z.missing"])
    }

    private func loadFixture(_ content: String) throws -> XCStringsFile {
        let data = content.data(using: .utf8)!
        return try JSONDecoder().decode(XCStringsFile.self, from: data)
    }

    private func stringEntry(sourceValue: String) -> StringEntry {
        StringEntry(
            localizations: [
                "en": Localization(
                    stringUnit: StringUnit(value: sourceValue)
                )
            ]
        )
    }
}
