import Foundation

/// Test fixtures for xcstrings file testing
enum TestFixtures {
    /// Empty xcstrings file
    static let empty = """
    {
      "sourceLanguage": "en",
      "strings": {},
      "version": "1.0"
    }
    """

    /// Single key with single language
    static let singleKeySingleLang = """
    {
      "sourceLanguage": "en",
      "strings": {
        "Hello": {
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Hello"
              }
            }
          }
        }
      },
      "version": "1.0"
    }
    """

    /// Single key with multiple languages
    static let singleKeyMultipleLangs = """
    {
      "sourceLanguage": "en",
      "strings": {
        "Hello": {
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Hello"
              }
            },
            "ja": {
              "stringUnit": {
                "state": "translated",
                "value": "こんにちは"
              }
            },
            "de": {
              "stringUnit": {
                "state": "translated",
                "value": "Hallo"
              }
            }
          }
        }
      },
      "version": "1.0"
    }
    """

    /// Multiple keys with partial translations
    static let multipleKeysPartialTranslations = """
    {
      "sourceLanguage": "en",
      "strings": {
        "Hello": {
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Hello"
              }
            },
            "ja": {
              "stringUnit": {
                "state": "translated",
                "value": "こんにちは"
              }
            }
          }
        },
        "Goodbye": {
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Goodbye"
              }
            }
          }
        },
        "Welcome": {
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Welcome"
              }
            },
            "ja": {
              "stringUnit": {
                "state": "translated",
                "value": "ようこそ"
              }
            },
            "de": {
              "stringUnit": {
                "state": "translated",
                "value": "Willkommen"
              }
            }
          }
        }
      },
      "version": "1.0"
    }
    """

    /// Keys with comments
    static let withComments = """
    {
      "sourceLanguage": "en",
      "strings": {
        "Hello": {
          "comment": "Greeting message shown on home screen",
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Hello"
              }
            }
          }
        },
        "Save": {
          "comment": "Button label for saving data",
          "extractionState": "manual",
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Save"
              }
            }
          }
        }
      },
      "version": "1.0"
    }
    """

    /// File with a key that should not be translated
    static let withNonTranslatableKey = """
    {
      "sourceLanguage": "en",
      "strings": {
        "BrandName": {
          "comment": "Proper noun shown as-is in every locale",
          "isCommentAutoGenerated": true,
          "shouldTranslate": false
        },
        "Hello": {
          "comment": "Greeting",
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Hello"
              }
            },
            "ja": {
              "stringUnit": {
                "state": "translated",
                "value": "こんにちは"
              }
            }
          }
        }
      },
      "version": "1.0"
    }
    """

    /// File where a locale appears only on a non-translatable key
    static let withLocaleOnlyOnNonTranslatableKey = """
    {
      "sourceLanguage": "en",
      "strings": {
        "BrandName": {
          "comment": "Proper noun shown as-is in every locale",
          "shouldTranslate": false,
          "localizations": {
            "ja": {
              "stringUnit": {
                "state": "translated",
                "value": "BrandName"
              }
            }
          }
        },
        "Hello": {
          "comment": "Greeting",
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Hello"
              }
            }
          }
        }
      },
      "version": "1.0"
    }
    """

    /// Different source language (Japanese)
    static let japaneseSource = """
    {
      "sourceLanguage": "ja",
      "strings": {
        "こんにちは": {
          "localizations": {
            "ja": {
              "stringUnit": {
                "state": "translated",
                "value": "こんにちは"
              }
            },
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Hello"
              }
            }
          }
        }
      },
      "version": "1.0"
    }
    """

    /// Many keys (10 keys)
    static let manyKeys = """
    {
      "sourceLanguage": "en",
      "strings": {
        "Key1": { "localizations": { "en": { "stringUnit": { "state": "translated", "value": "Value1" } } } },
        "Key2": { "localizations": { "en": { "stringUnit": { "state": "translated", "value": "Value2" } } } },
        "Key3": { "localizations": { "en": { "stringUnit": { "state": "translated", "value": "Value3" } } } },
        "Key4": { "localizations": { "en": { "stringUnit": { "state": "translated", "value": "Value4" } } } },
        "Key5": { "localizations": { "en": { "stringUnit": { "state": "translated", "value": "Value5" } } } },
        "Key6": { "localizations": { "en": { "stringUnit": { "state": "translated", "value": "Value6" } }, "ja": { "stringUnit": { "state": "translated", "value": "値6" } } } },
        "Key7": { "localizations": { "en": { "stringUnit": { "state": "translated", "value": "Value7" } }, "ja": { "stringUnit": { "state": "translated", "value": "値7" } } } },
        "Key8": { "localizations": { "en": { "stringUnit": { "state": "translated", "value": "Value8" } }, "ja": { "stringUnit": { "state": "translated", "value": "値8" } } } },
        "Key9": { "localizations": { "en": { "stringUnit": { "state": "translated", "value": "Value9" } } } },
        "Key10": { "localizations": { "en": { "stringUnit": { "state": "translated", "value": "Value10" } } } }
      },
      "version": "1.0"
    }
    """

    /// Keys with special characters
    static let specialCharacters = """
    {
      "sourceLanguage": "en",
      "strings": {
        "Hello, %@!": {
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Hello, %@!"
              }
            },
            "ja": {
              "stringUnit": {
                "state": "translated",
                "value": "こんにちは、%@！"
              }
            }
          }
        },
        "Items: %lld": {
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Items: %lld"
              }
            }
          }
        },
        "Line1\\\\nLine2": {
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Line1\\\\nLine2"
              }
            }
          }
        }
      },
      "version": "1.0"
    }
    """

    /// Keys with empty localizations
    static let emptyLocalizations = """
    {
      "sourceLanguage": "en",
      "strings": {
        "NoTranslation": {
          "comment": "This key has no translations yet"
        },
        "HasTranslation": {
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Has Translation"
              }
            }
          }
        }
      },
      "version": "1.0"
    }
    """

    /// Many languages (5+ languages)
    static let manyLanguages = """
    {
      "sourceLanguage": "en",
      "strings": {
        "Hello": {
          "localizations": {
            "en": { "stringUnit": { "state": "translated", "value": "Hello" } },
            "ja": { "stringUnit": { "state": "translated", "value": "こんにちは" } },
            "de": { "stringUnit": { "state": "translated", "value": "Hallo" } },
            "fr": { "stringUnit": { "state": "translated", "value": "Bonjour" } },
            "es": { "stringUnit": { "state": "translated", "value": "Hola" } },
            "zh-Hans": { "stringUnit": { "state": "translated", "value": "你好" } },
            "ko": { "stringUnit": { "state": "translated", "value": "안녕하세요" } }
          }
        }
      },
      "version": "1.0"
    }
    """

    /// Various translation states
    static let variousStates = """
    {
      "sourceLanguage": "en",
      "strings": {
        "Translated": {
          "localizations": {
            "en": { "stringUnit": { "state": "translated", "value": "Translated" } },
            "ja": { "stringUnit": { "state": "translated", "value": "翻訳済み" } }
          }
        },
        "NeedsReview": {
          "localizations": {
            "en": { "stringUnit": { "state": "translated", "value": "Needs Review" } },
            "ja": { "stringUnit": { "state": "needs_review", "value": "レビュー必要" } }
          }
        },
        "New": {
          "localizations": {
            "en": { "stringUnit": { "state": "new", "value": "New" } }
          }
        }
      },
      "version": "1.0"
    }
    """

    /// Keys with plural variations
    static let pluralVariations = """
    {
      "sourceLanguage": "en",
      "strings": {
        "%lld items": {
          "localizations": {
            "en": {
              "variations": {
                "plural": {
                  "one": {
                    "stringUnit": {
                      "state": "translated",
                      "value": "%lld item"
                    }
                  },
                  "other": {
                    "stringUnit": {
                      "state": "translated",
                      "value": "%lld items"
                    }
                  }
                }
              }
            },
            "ja": {
              "variations": {
                "plural": {
                  "other": {
                    "stringUnit": {
                      "state": "translated",
                      "value": "%lld個のアイテム"
                    }
                  }
                }
              }
            }
          }
        },
        "Hello": {
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Hello"
              }
            }
          }
        }
      },
      "version": "1.0"
    }
    """

    /// Keys with device variations
    static let deviceVariations = """
    {
      "sourceLanguage": "en",
      "strings": {
        "Start": {
          "localizations": {
            "en": {
              "variations": {
                "device": {
                  "iphone": {
                    "stringUnit": {
                      "state": "translated",
                      "value": "Tap to start"
                    }
                  },
                  "mac": {
                    "stringUnit": {
                      "state": "translated",
                      "value": "Click to start"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "version": "1.0"
    }
    """

    /// Keys with string catalog substitutions and extra metadata.
    static let withSubstitutions = """
    {
      "sourceLanguage": "en",
      "strings": {
        "plain.key": {
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Plain"
              }
            }
          }
        },
        "items.count": {
          "developerMetadata": {
            "domain": "catalog-fixture",
            "priority": 1
          },
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "%#@itemCount@"
              },
              "localizationNote": "preserve-localization-unknown-field",
              "substitutions": {
                "itemCount": {
                  "argNum": 1,
                  "formatSpecifier": "lld",
                  "substitutionNote": "preserve-substitution-unknown-field",
                  "variations": {
                    "plural": {
                      "one": {
                        "stringUnit": {
                          "state": "translated",
                          "value": "%arg item"
                        }
                      },
                      "other": {
                        "stringUnit": {
                          "state": "translated",
                          "value": "%arg items"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "version": "1.0"
    }
    """

    /// Keys with stale extraction state
    static let withStaleKeys = """
    {
      "sourceLanguage": "en",
      "strings": {
        "ActiveKey": {
          "localizations": {
            "en": { "stringUnit": { "state": "translated", "value": "Active" } }
          }
        },
        "StaleKey1": {
          "extractionState": "stale",
          "localizations": {
            "en": { "stringUnit": { "state": "translated", "value": "Stale 1" } }
          }
        },
        "StaleKey2": {
          "extractionState": "stale",
          "localizations": {
            "en": { "stringUnit": { "state": "translated", "value": "Stale 2" } },
            "ja": { "stringUnit": { "state": "translated", "value": "古い2" } }
          }
        },
        "ManualKey": {
          "extractionState": "manual",
          "localizations": {
            "en": { "stringUnit": { "state": "translated", "value": "Manual" } }
          }
        }
      },
      "version": "1.0"
    }
    """

    /// Mixed catalog used by the preflight classifier.
    static let preflightMixedCatalog = """
    {
      "sourceLanguage": "en",
      "strings": {
        "already.translated": {
          "comment": "A key that already has the target locale.",
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Already translated"
              }
            },
            "es": {
              "stringUnit": {
                "state": "translated",
                "value": "Ya traducido"
              }
            }
          }
        },
        "brand.name": {
          "comment": "A brand-like proper noun that should not be translated.",
          "shouldTranslate": false
        },
        "format.missing": {
          "comment": "Accessibility label with item name and count.",
          "extractionState": "manual",
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Item %1$@ has %2$lld matches"
              }
            }
          }
        },
        "plain.missing": {
          "comment": "Simple button title.",
          "isCommentAutoGenerated": true,
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Import"
              }
            }
          }
        },
        "stale.missing": {
          "comment": "A stale simple key.",
          "extractionState": "stale",
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Old Copy"
              }
            }
          }
        },
        "substitution.missing": {
          "comment": "Pluralized count through a substitution.",
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "%#@itemCount@"
              },
              "substitutions": {
                "itemCount": {
                  "argNum": 1,
                  "formatSpecifier": "lld",
                  "variations": {
                    "plural": {
                      "one": {
                        "stringUnit": {
                          "state": "translated",
                          "value": "%arg item"
                        }
                      },
                      "other": {
                        "stringUnit": {
                          "state": "translated",
                          "value": "%arg items"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "variation.missing": {
          "comment": "Pluralized count through direct variations.",
          "localizations": {
            "en": {
              "variations": {
                "plural": {
                  "one": {
                    "stringUnit": {
                      "state": "translated",
                      "value": "%lld item"
                    }
                  },
                  "other": {
                    "stringUnit": {
                      "state": "translated",
                      "value": "%lld items"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "version": "1.0"
    }
    """

    /// Derived from the temporary repo-root catalog so tests keep exercising a
    /// real catalog shape after that file is removed.
    static let realWorldSample = """
    {
      "sourceLanguage": "en",
      "strings": {
        "Hello, world!": {
          "comment": "A greeting displayed in the main view.",
          "isCommentAutoGenerated": true,
          "shouldTranslate": false
        },
        "SwiftUI makes small UI changes fast.": {
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "SwiftUI makes small UI changes fast."
              }
            },
            "ja": {
              "stringUnit": {
                "state": "translated",
                "value": "Japanese placeholder translation"
              }
            }
          }
        },
        "This view now has a bit more to say.": {
          "comment": "A description of the additional content in the `ContentView`.",
          "isCommentAutoGenerated": true,
          "localizations": {
            "fr": {
              "stringUnit": {
                "state": "translated",
                "value": "French placeholder translation"
              }
            },
            "ja": {
              "stringUnit": {
                "state": "needs_review",
                "value": "This view now has a bit more to say."
              }
            }
          }
        },
        "You can replace these lines with app content later.": {
          "comment": "A description of the content of the app.",
          "isCommentAutoGenerated": true,
          "shouldTranslate": false
        }
      },
      "version": "1.2"
    }
    """

    /// Minimal sample app catalog slice derived from local integration coverage.
    /// The key order intentionally catches sorted-key rewrites:
    /// - `sample.export.saved` must stay before `sample.export.saveCopyDetail`.
    /// - `sample.library.itemAccessibilityLabel` must stay before `sample.library.people`.
    static let catalogPersistenceRegression = """
    {
      "sourceLanguage" : "en",
      "strings" : {
        "sample.action.import" : {
          "comment" : "A button title for importing an item.",
          "extractionState" : "manual",
          "localizations" : {
            "en" : {
              "stringUnit" : {
                "state" : "translated",
                "value" : "Import"
              }
            }
          }
        },
        "sample.action.preview" : {
          "comment" : "A button title for previewing export output.",
          "extractionState" : "manual",
          "localizations" : {
            "en" : {
              "stringUnit" : {
                "state" : "translated",
                "value" : "Preview"
              }
            }
          }
        },
        "sample.export.saved" : {
          "comment" : "A transient status shown after writing an export to disk.",
          "extractionState" : "manual",
          "localizations" : {
            "en" : {
              "stringUnit" : {
                "state" : "translated",
                "value" : "Export saved"
              }
            }
          }
        },
        "sample.export.saveCopyDetail" : {
          "comment" : "An export action detail for saving a copy.",
          "extractionState" : "manual",
          "localizations" : {
            "en" : {
              "stringUnit" : {
                "state" : "translated",
                "value" : "Save as a new file with extra details removed."
              }
            }
          }
        },
        "sample.library.itemAccessibilityLabel" : {
          "comment" : "An accessibility label for an item thumbnail that includes creation date and pixel dimensions.",
          "extractionState" : "manual",
          "localizations" : {
            "en" : {
              "stringUnit" : {
                "state" : "translated",
                "value" : "Item, %1$@, %2$lld by %3$lld pixels"
              }
            }
          }
        },
        "sample.library.people" : {
          "comment" : "A sidebar library destination title.",
          "extractionState" : "manual",
          "localizations" : {
            "en" : {
              "stringUnit" : {
                "state" : "translated",
                "value" : "People"
              }
            }
          }
        }
      },
      "version" : "1.2"
    }
    """ + "\n"
}

/// Test helper utilities
enum TestHelper {
    /// Create a temporary file and return its path
    static func createTempFile(content: String) throws -> String {
        let tempDir = FileManager.default.temporaryDirectory
        let path = tempDir.appendingPathComponent("test_\(UUID().uuidString).xcstrings").path
        try content.write(toFile: path, atomically: true, encoding: .utf8)
        return path
    }

    /// Remove temporary file
    static func removeTempFile(at path: String) {
        try? FileManager.default.removeItem(atPath: path)
    }
}
