public enum SharedTestFixtures {
    /// Mixed catalog used by preflight classifier tests across Kit and MCP.
    public static let preflightMixedCatalog = """
    {
      "sourceLanguage": "en",
      "strings": {
        "already.translated": {
          "comment": "A key that already has the target locale.",
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Already translated"
              }
            },
            "es": {
              "stringUnit": {
                "state": "translated",
                "value": "Ya traducido"
              }
            }
          }
        },
        "brand.name": {
          "comment": "A brand-like proper noun that should not be translated.",
          "shouldTranslate": false
        },
        "format.missing": {
          "comment": "Accessibility label with item name and count.",
          "extractionState": "manual",
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Item %1$@ has %2$lld matches"
              }
            }
          }
        },
        "plain.missing": {
          "comment": "Simple button title.",
          "isCommentAutoGenerated": true,
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Import"
              }
            }
          }
        },
        "stale.missing": {
          "comment": "A stale simple key.",
          "extractionState": "stale",
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "Old Copy"
              }
            }
          }
        },
        "substitution.missing": {
          "comment": "Pluralized count through a substitution.",
          "localizations": {
            "en": {
              "stringUnit": {
                "state": "translated",
                "value": "%#@itemCount@"
              },
              "substitutions": {
                "itemCount": {
                  "argNum": 1,
                  "formatSpecifier": "lld",
                  "variations": {
                    "plural": {
                      "one": {
                        "stringUnit": {
                          "state": "translated",
                          "value": "%arg item"
                        }
                      },
                      "other": {
                        "stringUnit": {
                          "state": "translated",
                          "value": "%arg items"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "variation.missing": {
          "comment": "Pluralized count through direct variations.",
          "localizations": {
            "en": {
              "variations": {
                "plural": {
                  "one": {
                    "stringUnit": {
                      "state": "translated",
                      "value": "%lld item"
                    }
                  },
                  "other": {
                    "stringUnit": {
                      "state": "translated",
                      "value": "%lld items"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "version": "1.0"
    }
    """
}
