import Foundation

/// Read-only classifier for planning locale supplementation before any writes.
package struct XCStringsPreflightClassifier: Sendable {
    private let file: XCStringsFile

    package init(file: XCStringsFile) {
        self.file = file
    }

    package func preflightLocale(_ targetLanguage: String) -> PreflightLocaleReport {
        var missingSimpleStringUnitKeys: [PreflightKeyInfo] = []
        var missingFormatStringKeys: [PreflightKeyInfo] = []
        var missingVariationKeys: [PreflightKeyInfo] = []
        var missingSubstitutionKeys: [PreflightKeyInfo] = []
        var nonTranslatableKeys: [PreflightKeyInfo] = []
        var staleKeys: [PreflightKeyInfo] = []
        var translatedKeys: [PreflightKeyInfo] = []
        var unsafeToWriteKeys: [PreflightKeyInfo] = []

        for key in file.strings.keys.sorted() {
            guard let entry = file.strings[key] else {
                continue
            }

            let info = classify(key: key, entry: entry, targetLanguage: targetLanguage)

            if info.extractionState == "stale" {
                staleKeys.append(info)
            }

            if !entry.requiresTranslation {
                nonTranslatableKeys.append(info)
            } else if entry.countsAsTranslated(for: targetLanguage) {
                translatedKeys.append(info)
            } else {
                switch info.contentKind {
                case .simpleStringUnit:
                    missingSimpleStringUnitKeys.append(info)
                case .formatString:
                    missingFormatStringKeys.append(info)
                case .variation:
                    missingVariationKeys.append(info)
                case .substitution:
                    missingSubstitutionKeys.append(info)
                }
            }

            if info.writeSafety.isUnsafe {
                unsafeToWriteKeys.append(info)
            }
        }

        return PreflightLocaleReport(
            sourceLanguage: file.sourceLanguage,
            targetLanguage: targetLanguage,
            missingSimpleStringUnitKeys: missingSimpleStringUnitKeys,
            missingFormatStringKeys: missingFormatStringKeys,
            missingVariationKeys: missingVariationKeys,
            missingSubstitutionKeys: missingSubstitutionKeys,
            nonTranslatableKeys: nonTranslatableKeys,
            staleKeys: staleKeys,
            translatedKeys: translatedKeys,
            unsafeToWriteKeys: unsafeToWriteKeys
        )
    }

    private func classify(key: String, entry: StringEntry, targetLanguage: String) -> PreflightKeyInfo {
        let sourceLocalization = entry.localizations?[file.sourceLanguage]
        let targetLocalization = entry.localizations?[targetLanguage]
        let sourceValue = sourceLocalization?.stringUnit?.value ?? key
        let targetValue = targetLocalization?.stringUnit?.value
        let placeholderMetadata = placeholderMetadata(
            sourceValue: sourceValue,
            sourceLocalization: sourceLocalization
        )
        let contentKind = contentKind(
            sourceLocalization: sourceLocalization,
            placeholderMetadata: placeholderMetadata
        )
        let writeSafety = writeSafety(
            entry: entry,
            targetLanguage: targetLanguage,
            sourceLocalization: sourceLocalization,
            targetLocalization: targetLocalization,
            contentKind: contentKind
        )

        return PreflightKeyInfo(
            key: key,
            contentKind: contentKind,
            writeSafety: writeSafety,
            sourceValue: sourceValue,
            sourceState: sourceLocalization?.stringUnit?.state,
            targetValue: targetValue,
            targetState: targetLocalization?.stringUnit?.state,
            comment: entry.comment,
            isCommentAutoGenerated: entry.isCommentAutoGenerated,
            shouldTranslate: entry.shouldTranslate,
            extractionState: entry.extractionState,
            sourceHasVariations: sourceLocalization?.variations != nil,
            sourceHasSubstitutions: sourceLocalization?.substitutions != nil,
            targetHasVariations: targetLocalization?.variations != nil,
            targetHasSubstitutions: targetLocalization?.substitutions != nil,
            placeholderMetadata: placeholderMetadata
        )
    }

    private func contentKind(
        sourceLocalization: Localization?,
        placeholderMetadata: PreflightPlaceholderMetadata
    ) -> PreflightContentKind {
        if sourceLocalization?.substitutions != nil
            || placeholderMetadata.sourcePlaceholders.contains(where: { $0.kind == .stringsdictSubstitution }) {
            return .substitution
        }

        if sourceLocalization?.variations != nil {
            return .variation
        }

        if !placeholderMetadata.sourcePlaceholders.isEmpty {
            return .formatString
        }

        return .simpleStringUnit
    }

    private func writeSafety(
        entry: StringEntry,
        targetLanguage: String,
        sourceLocalization: Localization?,
        targetLocalization: Localization?,
        contentKind: PreflightContentKind
    ) -> PreflightWriteSafety {
        guard entry.requiresTranslation else {
            return PreflightWriteSafety(
                level: .nonTranslatable,
                reasons: [
                    "shouldTranslate is false; write operations intentionally refuse this key."
                ]
            )
        }

        if sourceLocalization?.hasRichContent == true || targetLocalization?.hasRichContent == true {
            return PreflightWriteSafety(
                level: .unsupportedRichLocalization,
                reasons: [
                    "The source or target localization uses variations or substitutions; current plain stringUnit writes are refused."
                ]
            )
        }

        switch contentKind {
        case .substitution, .variation:
            return PreflightWriteSafety(
                level: .unsupportedRichLocalization,
                reasons: [
                    "This key requires variation/substitution-aware writes; current plain stringUnit writes are refused."
                ]
            )
        case .formatString:
            return PreflightWriteSafety(
                level: .requiresFormatStringValidation,
                reasons: [
                    "The source contains format placeholders; translations must preserve placeholder identity."
                ]
            )
        case .simpleStringUnit:
            break
        }

        if entry.countsAsTranslated(for: targetLanguage) {
            return PreflightWriteSafety(
                level: .alreadyTranslated,
                reasons: [
                    "The target language already has a concrete localization; use update or overwrite intentionally."
                ]
            )
        }

        return PreflightWriteSafety(
            level: .safePlainStringUnit,
            reasons: [
                "Safe candidate for current plain stringUnit add_translation or batch_add_translations."
            ]
        )
    }

    private func placeholderMetadata(
        sourceValue: String,
        sourceLocalization: Localization?
    ) -> PreflightPlaceholderMetadata {
        PreflightPlaceholderMetadata(
            sourcePlaceholders: FormatStringSafety.placeholders(in: sourceValue),
            variationPlaceholders: variationPlaceholders(in: sourceLocalization?.variations),
            substitutions: substitutionMetadata(in: sourceLocalization?.substitutions)
        )
    }

    private func substitutionMetadata(
        in substitutions: OrderedStringDictionary<Substitution>?
    ) -> [PreflightSubstitutionMetadata] {
        guard let substitutions else {
            return []
        }

        return substitutions.map { name, substitution in
            PreflightSubstitutionMetadata(
                name: name,
                argNum: substitution.argNum,
                formatSpecifier: substitution.formatSpecifier,
                variationPlaceholders: variationPlaceholders(in: substitution.variations)
            )
        }
    }

    private func variationPlaceholders(in variations: Variations?) -> [PreflightVariationPlaceholderMetadata] {
        guard let variations else {
            return []
        }

        var result: [PreflightVariationPlaceholderMetadata] = []

        if let plural = variations.plural {
            result.append(contentsOf: variationValues(in: plural).map { category, value in
                PreflightVariationPlaceholderMetadata(
                    variationKind: "plural",
                    category: category,
                    value: value,
                    placeholders: FormatStringSafety.placeholders(in: value)
                )
            })
        }

        if let device = variations.device {
            result.append(contentsOf: variationValues(in: device).map { category, value in
                PreflightVariationPlaceholderMetadata(
                    variationKind: "device",
                    category: category,
                    value: value,
                    placeholders: FormatStringSafety.placeholders(in: value)
                )
            })
        }

        return result
    }

    private func variationValues(in plural: PluralVariation) -> [(category: String, value: String)] {
        [
            ("zero", plural.zero),
            ("one", plural.one),
            ("two", plural.two),
            ("few", plural.few),
            ("many", plural.many),
            ("other", plural.other),
        ].compactMap { category, variationValue in
            guard let value = variationValue?.stringUnit?.value else {
                return nil
            }
            return (category, value)
        }
    }

    private func variationValues(in device: DeviceVariation) -> [(category: String, value: String)] {
        [
            ("iphone", device.iphone),
            ("ipad", device.ipad),
            ("mac", device.mac),
            ("applewatch", device.applewatch),
            ("appletv", device.appletv),
        ].compactMap { category, variationValue in
            guard let value = variationValue?.stringUnit?.value else {
                return nil
            }
            return (category, value)
        }
    }
}

// MARK: - Preflight Output Models

package struct PreflightLocaleReport: Codable, Sendable {
    package let sourceLanguage: String
    package let targetLanguage: String
    package let summary: PreflightLocaleSummary
    package let missingSimpleStringUnitKeys: [PreflightKeyInfo]
    package let missingFormatStringKeys: [PreflightKeyInfo]
    package let missingVariationKeys: [PreflightKeyInfo]
    package let missingSubstitutionKeys: [PreflightKeyInfo]
    package let nonTranslatableKeys: [PreflightKeyInfo]
    package let staleKeys: [PreflightKeyInfo]
    package let translatedKeys: [PreflightKeyInfo]
    package let unsafeToWriteKeys: [PreflightKeyInfo]

    package init(
        sourceLanguage: String,
        targetLanguage: String,
        missingSimpleStringUnitKeys: [PreflightKeyInfo],
        missingFormatStringKeys: [PreflightKeyInfo],
        missingVariationKeys: [PreflightKeyInfo],
        missingSubstitutionKeys: [PreflightKeyInfo],
        nonTranslatableKeys: [PreflightKeyInfo],
        staleKeys: [PreflightKeyInfo],
        translatedKeys: [PreflightKeyInfo],
        unsafeToWriteKeys: [PreflightKeyInfo]
    ) {
        self.sourceLanguage = sourceLanguage
        self.targetLanguage = targetLanguage
        self.missingSimpleStringUnitKeys = missingSimpleStringUnitKeys
        self.missingFormatStringKeys = missingFormatStringKeys
        self.missingVariationKeys = missingVariationKeys
        self.missingSubstitutionKeys = missingSubstitutionKeys
        self.nonTranslatableKeys = nonTranslatableKeys
        self.staleKeys = staleKeys
        self.translatedKeys = translatedKeys
        self.unsafeToWriteKeys = unsafeToWriteKeys
        self.summary = PreflightLocaleSummary(
            missingSimpleStringUnitKeys: missingSimpleStringUnitKeys,
            missingFormatStringKeys: missingFormatStringKeys,
            missingVariationKeys: missingVariationKeys,
            missingSubstitutionKeys: missingSubstitutionKeys,
            nonTranslatableKeys: nonTranslatableKeys,
            staleKeys: staleKeys,
            translatedKeys: translatedKeys,
            unsafeToWriteKeys: unsafeToWriteKeys
        )
    }
}

package struct PreflightLocaleSummary: Codable, Sendable {
    package let totalKeys: Int
    package let translatableKeys: Int
    package let translatedKeys: Int
    package let untranslatedKeys: Int
    package let missingSimpleStringUnitKeys: Int
    package let missingFormatStringKeys: Int
    package let missingVariationKeys: Int
    package let missingSubstitutionKeys: Int
    package let nonTranslatableKeys: Int
    package let staleKeys: Int
    package let unsafeToWriteKeys: Int
    package let safeToBatchAddKeys: [String]
    package let formatStringKeysRequiringValidation: [String]
    package let richKeysRequiringSpecialHandling: [String]
    package let skipKeys: [String]

    package init(
        missingSimpleStringUnitKeys: [PreflightKeyInfo],
        missingFormatStringKeys: [PreflightKeyInfo],
        missingVariationKeys: [PreflightKeyInfo],
        missingSubstitutionKeys: [PreflightKeyInfo],
        nonTranslatableKeys: [PreflightKeyInfo],
        staleKeys: [PreflightKeyInfo],
        translatedKeys: [PreflightKeyInfo],
        unsafeToWriteKeys: [PreflightKeyInfo]
    ) {
        self.totalKeys = missingSimpleStringUnitKeys.count
            + missingFormatStringKeys.count
            + missingVariationKeys.count
            + missingSubstitutionKeys.count
            + nonTranslatableKeys.count
            + translatedKeys.count
        self.translatableKeys = totalKeys - nonTranslatableKeys.count
        self.translatedKeys = translatedKeys.count
        self.untranslatedKeys = missingSimpleStringUnitKeys.count
            + missingFormatStringKeys.count
            + missingVariationKeys.count
            + missingSubstitutionKeys.count
        self.missingSimpleStringUnitKeys = missingSimpleStringUnitKeys.count
        self.missingFormatStringKeys = missingFormatStringKeys.count
        self.missingVariationKeys = missingVariationKeys.count
        self.missingSubstitutionKeys = missingSubstitutionKeys.count
        self.nonTranslatableKeys = nonTranslatableKeys.count
        self.staleKeys = staleKeys.count
        self.unsafeToWriteKeys = unsafeToWriteKeys.count
        self.safeToBatchAddKeys = missingSimpleStringUnitKeys.map(\.key)
        self.formatStringKeysRequiringValidation = missingFormatStringKeys.map(\.key)
        self.richKeysRequiringSpecialHandling = (missingVariationKeys + missingSubstitutionKeys).map(\.key).sorted()
        self.skipKeys = nonTranslatableKeys.map(\.key)
    }
}

package enum PreflightContentKind: String, Codable, Sendable {
    case simpleStringUnit
    case formatString
    case variation
    case substitution
}

package enum PreflightWriteSafetyLevel: String, Codable, Sendable {
    case safePlainStringUnit
    case requiresFormatStringValidation
    case unsupportedRichLocalization
    case nonTranslatable
    case alreadyTranslated
}

package struct PreflightWriteSafety: Codable, Sendable {
    package let level: PreflightWriteSafetyLevel
    package let reasons: [String]

    package init(level: PreflightWriteSafetyLevel, reasons: [String]) {
        self.level = level
        self.reasons = reasons
    }

    package var isUnsafe: Bool {
        level == .unsupportedRichLocalization || level == .nonTranslatable
    }
}

package struct PreflightKeyInfo: Codable, Sendable {
    package let key: String
    package let contentKind: PreflightContentKind
    package let writeSafety: PreflightWriteSafety
    package let sourceValue: String
    package let sourceState: String?
    package let targetValue: String?
    package let targetState: String?
    package let comment: String?
    package let isCommentAutoGenerated: Bool?
    package let shouldTranslate: Bool?
    package let extractionState: String?
    package let sourceHasVariations: Bool
    package let sourceHasSubstitutions: Bool
    package let targetHasVariations: Bool
    package let targetHasSubstitutions: Bool
    package let placeholderMetadata: PreflightPlaceholderMetadata

    package init(
        key: String,
        contentKind: PreflightContentKind,
        writeSafety: PreflightWriteSafety,
        sourceValue: String,
        sourceState: String?,
        targetValue: String?,
        targetState: String?,
        comment: String?,
        isCommentAutoGenerated: Bool?,
        shouldTranslate: Bool?,
        extractionState: String?,
        sourceHasVariations: Bool,
        sourceHasSubstitutions: Bool,
        targetHasVariations: Bool,
        targetHasSubstitutions: Bool,
        placeholderMetadata: PreflightPlaceholderMetadata
    ) {
        self.key = key
        self.contentKind = contentKind
        self.writeSafety = writeSafety
        self.sourceValue = sourceValue
        self.sourceState = sourceState
        self.targetValue = targetValue
        self.targetState = targetState
        self.comment = comment
        self.isCommentAutoGenerated = isCommentAutoGenerated
        self.shouldTranslate = shouldTranslate
        self.extractionState = extractionState
        self.sourceHasVariations = sourceHasVariations
        self.sourceHasSubstitutions = sourceHasSubstitutions
        self.targetHasVariations = targetHasVariations
        self.targetHasSubstitutions = targetHasSubstitutions
        self.placeholderMetadata = placeholderMetadata
    }
}

package struct PreflightPlaceholderMetadata: Codable, Sendable {
    package let sourcePlaceholders: [FormatPlaceholder]
    package let variationPlaceholders: [PreflightVariationPlaceholderMetadata]
    package let substitutions: [PreflightSubstitutionMetadata]

    package init(
        sourcePlaceholders: [FormatPlaceholder],
        variationPlaceholders: [PreflightVariationPlaceholderMetadata],
        substitutions: [PreflightSubstitutionMetadata]
    ) {
        self.sourcePlaceholders = sourcePlaceholders
        self.variationPlaceholders = variationPlaceholders
        self.substitutions = substitutions
    }
}

package struct PreflightSubstitutionMetadata: Codable, Sendable {
    package let name: String
    package let argNum: Int?
    package let formatSpecifier: String?
    package let variationPlaceholders: [PreflightVariationPlaceholderMetadata]

    package init(
        name: String,
        argNum: Int?,
        formatSpecifier: String?,
        variationPlaceholders: [PreflightVariationPlaceholderMetadata]
    ) {
        self.name = name
        self.argNum = argNum
        self.formatSpecifier = formatSpecifier
        self.variationPlaceholders = variationPlaceholders
    }
}

package struct PreflightVariationPlaceholderMetadata: Codable, Sendable {
    package let variationKind: String
    package let category: String
    package let value: String
    package let placeholders: [FormatPlaceholder]

    package init(
        variationKind: String,
        category: String,
        value: String,
        placeholders: [FormatPlaceholder]
    ) {
        self.variationKind = variationKind
        self.category = category
        self.value = value
        self.placeholders = placeholders
    }
}
