import Foundation

/// Handles read operations for xcstrings files
struct XCStringsReader: Sendable {
    private let file: XCStringsFile

    init(file: XCStringsFile) {
        self.file = file
    }

    /// Get all keys sorted alphabetically
    func listKeys() -> [String] {
        file.strings.keys.sorted()
    }

    /// Get all languages used in the file
    func listLanguages() -> [String] {
        file.strings.values.lazy
            .compactMap(\.localizations?.keys)
            .reduce(into: Set([file.sourceLanguage])) { $0.formUnion($1) }
            .sorted()
    }

    /// Get languages that are in scope for translatable entries.
    /// Excludes locales that appear only on `shouldTranslate: false` keys so they
    /// don't pollute coverage math against translatable keys.
    func listTranslatableLanguages() -> [String] {
        file.strings.values.lazy
            .filter(\.requiresTranslation)
            .compactMap(\.localizations?.keys)
            .reduce(into: Set([file.sourceLanguage])) { $0.formUnion($1) }
            .sorted()
    }

    /// Get untranslated keys for a specific language
    func listUntranslated(for language: String) -> [String] {
        file.strings
            .filter { _, entry in
                entry.requiresTranslation && !entry.countsAsTranslated(for: language)
            }
            .keys
            .sorted()
    }

    /// Get keys with stale extraction state
    func listStaleKeys() -> [String] {
        file.strings
            .filter { $0.value.extractionState == "stale" }
            .map { $0.key }
            .sorted()
    }

    /// Get source language
    func getSourceLanguage() -> String {
        file.sourceLanguage
    }

    /// Get key information
    func getKey(_ key: String, language: String? = nil) throws -> KeyInfo {
        guard let entry = file.strings[key] else {
            throw XCStringsError.keyNotFound(key: key)
        }

        let translations = keyInfoTranslations(for: key, entry: entry, language: language)
        let languages = translations.keys.sorted()

        return KeyInfo(
            key: key,
            comment: entry.comment,
            isCommentAutoGenerated: entry.isCommentAutoGenerated,
            shouldTranslate: entry.shouldTranslate,
            extractionState: entry.extractionState,
            languages: languages,
            translations: translations
        )
    }

    /// Get translation for a key
    func getTranslation(key: String, language: String?) throws -> [String: TranslationInfo] {
        guard let entry = file.strings[key] else {
            throw XCStringsError.keyNotFound(key: key)
        }

        return try strictTranslations(for: key, entry: entry, language: language)
    }

    /// Check if a key exists
    func checkKey(_ key: String, language: String?) -> Bool {
        guard let entry = file.strings[key] else {
            return false
        }

        if let lang = language {
            return entry.localizations?[lang] != nil
        }

        return true
    }

    /// Check if multiple keys exist
    func checkKeys(_ keys: [String], language: String?) -> BatchCheckKeysResult {
        let results = Dictionary(uniqueKeysWithValues: keys.lazy.map { ($0, checkKey($0, language: language)) })
        return BatchCheckKeysResult(results: results)
    }

    /// Check coverage for a key
    func checkCoverage(_ key: String) throws -> CoverageInfo {
        let allLanguages = listTranslatableLanguages()

        guard let entry = file.strings[key] else {
            throw XCStringsError.keyNotFound(key: key)
        }

        if !entry.requiresTranslation {
            return CoverageInfo(
                key: key,
                translatedLanguages: [],
                missingLanguages: [],
                coverage: .notApplicable
            )
        }

        let translatedLanguages = allLanguages.filter { entry.countsAsTranslated(for: $0) }
        let missingLanguages = allLanguages.filter { !translatedLanguages.contains($0) }
        let coverage = CoverageMeasurement.measured(
            allLanguages.isEmpty ? 0 : Double(translatedLanguages.count) / Double(allLanguages.count) * 100
        )

        return CoverageInfo(
            key: key,
            translatedLanguages: translatedLanguages,
            missingLanguages: missingLanguages,
            coverage: coverage
        )
    }

    private func strictTranslations(for key: String, entry: StringEntry, language: String?) throws -> [String: TranslationInfo] {
        if let lang = language {
            guard let localization = entry.localizations?[lang] else {
                throw XCStringsError.languageNotFound(language: lang, key: key)
            }

            return [lang: translationInfo(for: key, language: lang, localization: localization)]
        }

        return filteredTranslations(for: key, entry: entry, language: nil)
    }

    private func keyInfoTranslations(for key: String, entry: StringEntry, language: String?) -> [String: TranslationInfo] {
        filteredTranslations(for: key, entry: entry, language: language)
    }

    private func filteredTranslations(for key: String, entry: StringEntry, language: String?) -> [String: TranslationInfo] {
        if let lang = language {
            guard let localization = entry.localizations?[lang] else {
                return [:]
            }

            return [lang: translationInfo(for: key, language: lang, localization: localization)]
        }

        guard let localizations = entry.localizations else {
            return [:]
        }

        return Dictionary(uniqueKeysWithValues: localizations.map { lang, localization in
            (lang, translationInfo(for: key, language: lang, localization: localization))
        })
    }

    private func translationInfo(for key: String, language: String, localization: Localization) -> TranslationInfo {
        TranslationInfo(
            key: key,
            language: language,
            value: localization.stringUnit?.value,
            state: localization.stringUnit?.state,
            hasVariations: localization.variations != nil
        )
    }
}

private extension StringEntry {
    var requiresTranslation: Bool {
        shouldTranslate != false
    }

    func countsAsTranslated(for language: String) -> Bool {
        guard requiresTranslation else {
            return true
        }

        let localization = localizations?[language]
        return localization?.stringUnit?.value != nil || localization?.variations != nil
    }
}
