import Foundation

enum XCStringsJSONSerializer {
    static func data(for file: XCStringsFile, appendTrailingNewline: Bool) throws -> Data {
        var text = try render(file).joined(separator: "\n")
        if appendTrailingNewline, !text.hasSuffix("\n") {
            text.append("\n")
        }

        guard let data = text.data(using: .utf8) else {
            throw XCStringsError.serializationError(reason: "Failed to encode JSON as UTF-8")
        }
        return data
    }

    private static func render(_ file: XCStringsFile) throws -> [String] {
        try object([
            ("sourceLanguage", .string(file.sourceLanguage)),
            ("strings", .object(file.strings.map { key, entry in
                (key, stringEntry(entry))
            })),
            ("version", .string(file.version)),
        ], indent: 0)
    }

    private static func stringEntry(_ entry: StringEntry) -> JSONValue {
        var fields: [(String, JSONValue)] = []

        if let comment = entry.comment {
            fields.append(("comment", .string(comment)))
        }
        if let isCommentAutoGenerated = entry.isCommentAutoGenerated {
            fields.append(("isCommentAutoGenerated", .bool(isCommentAutoGenerated)))
        }
        if let shouldTranslate = entry.shouldTranslate {
            fields.append(("shouldTranslate", .bool(shouldTranslate)))
        }
        if let extractionState = entry.extractionState {
            fields.append(("extractionState", .string(extractionState)))
        }
        if let localizations = entry.localizations {
            fields.append(("localizations", .object(localizations.map { language, localization in
                (language, localizationValue(localization))
            })))
        }
        fields.append(contentsOf: rawFields(entry.unknownFields))

        return .object(fields)
    }

    private static func localizationValue(_ localization: Localization) -> JSONValue {
        var fields: [(String, JSONValue)] = []

        if let stringUnit = localization.stringUnit {
            fields.append(("stringUnit", stringUnitValue(stringUnit)))
        }
        if let variations = localization.variations {
            fields.append(("variations", variationsValue(variations)))
        }
        if let substitutions = localization.substitutions {
            fields.append(("substitutions", .object(substitutions.map { name, substitution in
                (name, substitutionValue(substitution))
            })))
        }
        fields.append(contentsOf: rawFields(localization.unknownFields))

        return .object(fields)
    }

    private static func stringUnitValue(_ stringUnit: StringUnit) -> JSONValue {
        var fields: [(String, JSONValue)] = [
            ("state", .string(stringUnit.state)),
            ("value", .string(stringUnit.value)),
        ]
        fields.append(contentsOf: rawFields(stringUnit.unknownFields))
        return .object(fields)
    }

    private static func variationsValue(_ variations: Variations) -> JSONValue {
        var fields: [(String, JSONValue)] = []

        if let plural = variations.plural {
            fields.append(("plural", pluralVariationValue(plural)))
        }
        if let device = variations.device {
            fields.append(("device", deviceVariationValue(device)))
        }
        fields.append(contentsOf: rawFields(variations.unknownFields))

        return .object(fields)
    }

    private static func pluralVariationValue(_ plural: PluralVariation) -> JSONValue {
        var fields: [(String, JSONValue)] = []

        if let zero = plural.zero {
            fields.append(("zero", variationValue(zero)))
        }
        if let one = plural.one {
            fields.append(("one", variationValue(one)))
        }
        if let two = plural.two {
            fields.append(("two", variationValue(two)))
        }
        if let few = plural.few {
            fields.append(("few", variationValue(few)))
        }
        if let many = plural.many {
            fields.append(("many", variationValue(many)))
        }
        if let other = plural.other {
            fields.append(("other", variationValue(other)))
        }
        fields.append(contentsOf: rawFields(plural.unknownFields))

        return .object(fields)
    }

    private static func deviceVariationValue(_ device: DeviceVariation) -> JSONValue {
        var fields: [(String, JSONValue)] = []

        if let iphone = device.iphone {
            fields.append(("iphone", variationValue(iphone)))
        }
        if let ipad = device.ipad {
            fields.append(("ipad", variationValue(ipad)))
        }
        if let mac = device.mac {
            fields.append(("mac", variationValue(mac)))
        }
        if let applewatch = device.applewatch {
            fields.append(("applewatch", variationValue(applewatch)))
        }
        if let appletv = device.appletv {
            fields.append(("appletv", variationValue(appletv)))
        }
        fields.append(contentsOf: rawFields(device.unknownFields))

        return .object(fields)
    }

    private static func variationValue(_ value: VariationValue) -> JSONValue {
        var fields: [(String, JSONValue)] = []

        if let stringUnit = value.stringUnit {
            fields.append(("stringUnit", stringUnitValue(stringUnit)))
        }
        fields.append(contentsOf: rawFields(value.unknownFields))

        return .object(fields)
    }

    private static func substitutionValue(_ substitution: Substitution) -> JSONValue {
        var fields: [(String, JSONValue)] = []

        if let argNum = substitution.argNum {
            fields.append(("argNum", .number(String(argNum))))
        }
        if let formatSpecifier = substitution.formatSpecifier {
            fields.append(("formatSpecifier", .string(formatSpecifier)))
        }
        if let variations = substitution.variations {
            fields.append(("variations", variationsValue(variations)))
        }
        fields.append(contentsOf: rawFields(substitution.unknownFields))

        return .object(fields)
    }

    private static func rawFields(_ fields: OrderedStringDictionary<XCStringsRawJSONValue>) -> [(String, JSONValue)] {
        fields.map { key, value in
            (key, rawValue(value))
        }
    }

    private static func rawValue(_ value: XCStringsRawJSONValue) -> JSONValue {
        switch value {
        case .string(let string):
            .string(string)
        case .bool(let bool):
            .bool(bool)
        case .int(let int):
            .number(String(int))
        case .double(let double):
            .number(String(double))
        case .object(let object):
            .object(rawFields(object))
        case .array(let values):
            .array(values.map(rawValue))
        case .null:
            .null
        }
    }

    private static func object(_ fields: [(String, JSONValue)], indent: Int) throws -> [String] {
        let padding = String(repeating: " ", count: indent)
        let childPadding = String(repeating: " ", count: indent + 2)

        guard !fields.isEmpty else {
            return ["\(padding){", "\(padding)}"]
        }

        var lines = ["\(padding){"]

        for (index, field) in fields.enumerated() {
            let valueLines = try render(field.1, indent: indent + 2)
            let comma = index == fields.count - 1 ? "" : ","
            let key = try quoted(field.0)

            if field.1.isScalar {
                lines.append("\(childPadding)\(key) : \(valueLines[0])\(comma)")
            } else {
                let firstValueLine = valueLines[0].dropFirst(childPadding.count)
                lines.append("\(childPadding)\(key) : \(firstValueLine)")
                lines.append(contentsOf: valueLines.dropFirst().dropLast())
                lines.append("\(valueLines.last!)\(comma)")
            }
        }

        lines.append("\(padding)}")
        return lines
    }

    private static func render(_ value: JSONValue, indent: Int) throws -> [String] {
        switch value {
        case .string(let string):
            [try quoted(string)]
        case .bool(let bool):
            [bool ? "true" : "false"]
        case .number(let number):
            [number]
        case .array(let values):
            try array(values, indent: indent)
        case .null:
            ["null"]
        case .object(let fields):
            try object(fields, indent: indent)
        }
    }

    private static func array(_ values: [JSONValue], indent: Int) throws -> [String] {
        let padding = String(repeating: " ", count: indent)
        let childPadding = String(repeating: " ", count: indent + 2)

        guard !values.isEmpty else {
            return ["\(padding)[]"]
        }

        var lines = ["\(padding)["]

        for (index, value) in values.enumerated() {
            let valueLines = try render(value, indent: indent + 2)
            let comma = index == values.count - 1 ? "" : ","

            if value.isScalar {
                lines.append("\(childPadding)\(valueLines[0])\(comma)")
            } else {
                lines.append(contentsOf: valueLines.dropLast())
                lines.append("\(valueLines.last!)\(comma)")
            }
        }

        lines.append("\(padding)]")
        return lines
    }

    private static func quoted(_ string: String) throws -> String {
        let data = try JSONEncoder().encode(string)
        guard let text = String(data: data, encoding: .utf8) else {
            throw XCStringsError.serializationError(reason: "Failed to quote JSON string")
        }
        return text
    }

    private enum JSONValue {
        case string(String)
        case bool(Bool)
        case number(String)
        case array([JSONValue])
        case null
        case object([(String, JSONValue)])

        var isScalar: Bool {
            switch self {
            case .string, .bool, .number, .null:
                return true
            case .array, .object:
                return false
            }
        }
    }
}
